'use client';

import { getConsentState } from '@/lib/consent/consentClient';

import { META_EVENTS, type MetaEventName } from './eventNames';
import { trackEvent } from './fbq';

/**
 * Client-side Meta pixel helpers.
 *
 * Event-name literals live in the neutral `eventNames` module (server-safe)
 * and are re-exported here so the browser pixel and CAPI share one source of
 * truth for dedup on (event_name, event_id).
 */
export { META_EVENTS, type MetaEventName };

/** Typed custom_data payloads for the browser-side events. */
export interface ViewContentData {
  content_type: 'product';
  content_name: string;
  content_ids?: string[];
  value?: number;
  currency?: string;
}

export interface InitiateCheckoutData {
  value?: number;
  currency?: string;
  contents?: { id: string; quantity: number }[];
}

export interface PurchaseData {
  value: number;
  currency: string;
  contents?: { id: string; quantity: number }[];
}

/**
 * Fires a PageView. No-op unless consent is `accepted` and the pixel was
 * initialized (race safety lives in fbq.ts). `eventID` is optional: PageView
 * is browser-only, so a dedup id is not required, but the parameter keeps
 * the helper API uniform with the CAPI-shared events.
 */
export function trackPageView(eventID?: string): void {
  if (getConsentState() !== 'accepted') return;
  trackEvent(META_EVENTS.pageView, undefined, eventID);
}

/**
 * Fires a ViewContent with typed custom data. No-op unless consent is
 * `accepted` and the pixel was initialized.
 */
export function trackViewContent(data: ViewContentData, eventID?: string): void {
  if (getConsentState() !== 'accepted') return;
  trackEvent(META_EVENTS.viewContent, { ...data }, eventID);
}

/**
 * Fires an InitiateCheckout with typed custom data. Browser-only: it gets its
 * OWN event id (no server twin), generated by the caller.
 */
export function trackInitiateCheckout(data: InitiateCheckoutData, eventID?: string): void {
  if (getConsentState() !== 'accepted') return;
  trackEvent(META_EVENTS.initiateCheckout, { ...data }, eventID);
}

/**
 * Fires a Purchase with typed custom data. The `eventID` MUST be the same id
 * the server used for the CAPI Purchase (see purchase-plan route), so Meta
 * deduplicates the pixel and server copies within its 48h window.
 */
export function trackPurchase(data: PurchaseData, eventID?: string): void {
  if (getConsentState() !== 'accepted') return;
  trackEvent(META_EVENTS.purchase, { ...data }, eventID);
}
